- name: Setup Apache Server
  hosts: localhost
  tasks:
    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Httpd on Amazon
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "Amazon"

    - name: Install Httpd on Redhat OS
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"

  handlers:
    - name: Install Apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install Httpd on Amazon
      service:
        name: httpd
        state: started
        enabled: yes
         
    - name: Install Httpd on Redhat OS
      service:
        name: httpd
        state: started
        enabled: yes